#pragma once

// RENDERER SETTING
const int RENDERER_WIDTH = 1440;
const int RENDERER_HEIGHT = 810;

const int RENDERER_CENTER_X = RENDERER_WIDTH / 2;
const int RENDERER_CENTER_Y = RENDERER_HEIGHT / 2;

//ANIMATION SETTING

const int FADING_IN_TRANSITION_TICKS = 500;
const int FADING_OUT_TRANSITION_TICKS = 500;

const int TITLE_COOLDOWN_TICKS = 500;

const int POINT_LONGEVITY = 500;

//GAME DATA
const int MAX_LIVES = 3;

const float COMBO_MULTIPLICATION_MULTIPLIER = 0.02f;
const float COMBO_MULTIPLICATION_BASE = 0.01f;
const float COMBO_MULTIPLICATION_MAX = 0.05f;

const int COMBO_DURATION_BASE = 1000;
const int COMBO_DURATION_MULTIPLIER = 20;
const int COMBO_DURATION_MAX = 2000;

//ENEMY SETTING

const int ENEMY_SPAWN_INTERVAL_BASE = 1000;
const int ENEMY_SPAWN_INTERVAL_MULTIPLIER = 1;
const int ENEMY_SPAWN_INTERVAL_MAX = 600;

const float ENEMY_SPAWN_BASE_RATE = 0.4f;
const float ENEMY_SPAWN_RATE_MULTIPLIER = 0.01f;
const float ENEMY_SPAWN_RATE_MAX = 0.9f;

const int ENEMY_BASE_SPEED = 250;
const int ENEMY_SPEED_MULTIPLIER = 5;
const int ENEMY_SPEED_MAX = 500;

const int ENTITY_DEATH_IMPACT = 400;
const int ENTITY_KILL_IMPACT = 400;

const int GRAVITY_SPEED = 250;

const int PARTICLE_ALIVE_TICK = 1000;